import { chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { writePrivateFileAtomicSync } from "../server/private-files.js";
import {
  buildHarnessShimEnv,
  CLIPROXYAPI_SHIM_DISABLE_ENV,
  shimConflictEnv,
  SHIMMED_HARNESSES,
  type ShimmedHarness,
} from "./harness-shims.js";
import type { ResolvedGatewayConfig } from "../server/agent/gateway/config.js";

/**
 * Generates the terminal harness shims into a private per-daemon directory and
 * prepends that directory to terminal PATH.
 *
 * The generated script is a POSIX `sh` wrapper. It resolves the real binary
 * from PATH with its own directory removed, so a shim can never recurse into
 * itself, then execs it with the gateway env and argv applied.
 */

const SHIM_DIR_BASENAME = "harness-shims";

/** Directory name of the real binary each shim must exec, past itself. */
const REAL_BINARY: Record<ShimmedHarness, string> = {
  claude: "claude",
  codex: "codex",
  opencode: "opencode",
};

function shimDirNameForPlatform(): string {
  // Windows shims need a .cmd wrapper; POSIX needs a bare executable.
  return process.platform === "win32" ? "cmd-shims" : SHIM_DIR_BASENAME;
}

export function resolveHarnessShimDirectory(paseoHome: string): string {
  return join(paseoHome, shimDirNameForPlatform());
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Emit a cmd.exe shim.
 *
 * The wrapper is named `claude.cmd` so a bare `claude` reaches it, and it strips
 * its own directory from PATH before launching the real binary — that strip is
 * the only thing keeping the wrapper from resolving to itself. The PATHEXT claim
 * in the old comment here was never verified on Windows and is not relied on:
 * the shim directory is prepended to PATH, and the real binary is reached by its
 * own absolute directory minus the shim directory.
 */
export function buildCmdShimScript(
  harness: ShimmedHarness,
  gateway: ResolvedGatewayConfig,
): string {
  const { env, argv } = buildHarnessShimEnv(harness, gateway);
  const realBinary = `${REAL_BINARY[harness]}.exe`;

  // A double quote inside `set "K=V"` is escaped with a backslash, not a caret.
  // A caret works for a space or an &, but before the closing quote it escapes
  // the quote itself and swallows the rest of the line. OpenCode's config
  // content is JSON, so it hits this on every invocation.
  const envLines = Object.entries(env).map(
    ([key, value]) => `set "${key}=${value.replace(/(["\r\n])/g, "\\$1")}"`,
  );

  // A terminal that already routes this harness keeps doing so. Whole-harness
  // rather than per-variable, so a user's OPENAI_API_KEY is never left pointing
  // at a gateway they did not ask for.
  const passthroughGuards = shimConflictEnv(harness).map(
    (key) => `if defined ${key} goto passthrough`,
  );

  return [
    "@echo off",
    // The strip loop reads and rewrites PATH between iterations, so it needs
    // !VAR! to expand at execution time. Without this every reference below is
    // the literal text "!PATH!", and the shim writes it back into the real
    // process env.
    "setlocal EnableExtensions EnableDelayedExpansion",
    `rem Generated by Paseo. Routes ${REAL_BINARY[harness]} through CLIProxyAPI for terminal sessions.`,
    `rem Bypass for a single run: set ${CLIPROXYAPI_SHIM_DISABLE_ENV}=1 && ${REAL_BINARY[harness]}`,
    `if "%${CLIPROXYAPI_SHIM_DISABLE_ENV}%"=="1" goto passthrough`,
    ...passthroughGuards,
    ...envLines,
    // `call`, not a spliced copy of the block: the strip lives in one
    // subroutine so the two launch paths cannot disagree, and so its
    // `goto :eof` returns here instead of ending the script before the
    // real binary ever runs.
    "call :stripSelfFromPath",
    `${realBinary} ${argv.map(quoteCmdArg).join(" ")} %*`,
    "exit /b %ERRORLEVEL%",
    "rem Nothing to inject: the user opted out, or the terminal already routes this harness.",
    ":passthrough",
    "call :stripSelfFromPath",
    `${realBinary} %*`,
    "exit /b %ERRORLEVEL%",
    // PATH is captured whole before the loop rewrites it, because %PATH%
    // expands once at parse time and would re-add the entries already removed.
    // `for /f` reads a single line and splits it on one delimiter, so it cannot
    // both split on `;` and keep the remainder in one pass; the loop peels the
    // head off and reassembles.
    ":stripSelfFromPath",
    'set "self_path=!PATH!"',
    'set "self_dir=%~dp0"',
    // %~dp0 always ends in a backslash and a PATH segment never does, so both
    // sides are normalized before the comparison. This is why the match is
    // exact: an earlier substring match could not tell the shim directory from
    // a longer path that merely started with it.
    //
    // The trailing backslash is tested unquoted. cmd.exe has no escape
    // character, so a quoted "\" closes the quote early and the test never
    // matches, which would leave the shim directory in PATH.
    'if "!self_dir:~-1!"==\\ goto trimSelfSlash',
    "goto selfDirReady",
    ":trimSelfSlash",
    'set "self_dir=!self_dir:~0,-1!"',
    ":selfDirReady",
    'set "rest=!PATH!"',
    'set "stripped="',
    ":stripLoop",
    "if not defined rest goto stripDone",
    'set "head="',
    'set "tail="',
    'for /f "tokens=1* delims=;" %%A in ("!rest!") do (',
    '  set "head=%%A"',
    '  set "tail=%%B"',
    ")",
    'set "rest=!tail!"',
    // Empty on a trailing `;`, which also ends the loop: a blank line is
    // skipped by for /f, so neither head nor tail is filled.
    "if not defined head goto stripLoop",
    'call :keepEntry "!head!"',
    "goto stripLoop",
    ":stripDone",
    "if not defined stripped goto restoreOriginalPath",
    'set "PATH=!stripped!"',
    "goto :eof",
    // PATH held nothing but this shim. Restoring beats leaving the child with
    // an empty PATH.
    ":restoreOriginalPath",
    'set "PATH=!self_path!"',
    "goto :eof",
    "rem Keep one PATH entry, unless it is this shim's own directory.",
    ":keepEntry",
    'set "entry=%~1"',
    'if "!entry:~-1!"==\\ set "entry=!entry:~0,-1!"',
    'if /I "!entry!"=="!self_dir!" goto :eof',
    "if not defined stripped goto keepFirstEntry",
    'set "stripped=!stripped!;%~1"',
    "goto :eof",
    ":keepFirstEntry",
    'set "stripped=%~1"',
    "goto :eof",
    "",
  ].join("\r\n");
}

function quoteCmdArg(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

/**
 * Emit a POSIX sh shim that execs the real binary with gateway env applied.
 *
 * `selfDir` is stripped from PATH so `command -v` skips this wrapper; without
 * that the shim resolves itself and recurses forever.
 */
function buildShimScript(harness: ShimmedHarness, gateway: ResolvedGatewayConfig): string {
  const { env, argv } = buildHarnessShimEnv(harness, gateway);
  const realBinary = REAL_BINARY[harness];

  const envExports = Object.entries(env)
    .map(([key, value]) => `export ${key}=${shellQuote(value)}`)
    .join("\n");

  const bypassTest = `\${${CLIPROXYAPI_SHIM_DISABLE_ENV}:-}`;

  // A terminal that already routes this harness keeps doing so. Whole-harness
  // rather than per-variable, so a user's OPENAI_API_KEY is never left pointing
  // at a gateway they did not ask for.
  const passthroughTests = shimConflictEnv(harness)
    .map((key) => `[ -n "\${${key}:-}" ]`)
    .join(" || ");

  // Drop this shim's own directory from PATH so `command -v` finds the real
  // binary instead of this wrapper. Without it the shim execs itself forever.
  //
  // Pure parameter expansion, deliberately: an earlier version piped PATH
  // through dirname/tr/grep/paste, but those run *after* PATH is rewritten and
  // vanished under a minimal PATH, breaking every invocation. The original
  // PATH is stashed in self_path and only the child inherits the stripped one.
  //
  // self_dir is derived from $0, which every common shell (sh, bash, dash, zsh)
  // fills with the PATH-resolved path even for a bare `claude`. Deriving it
  // from an env var instead would be a second source of truth for no gain.
  const stripSelfFromPath = `self_dir=\${0%/*}
self_path=$PATH
stripped=
rest=$PATH
while [ -n "$rest" ]; do
  entry=\${rest%%:*}
  if [ -n "$entry" ] && [ "$entry" != "$self_dir" ]; then
    if [ -n "$stripped" ]; then stripped=$stripped:$entry; else stripped=$entry; fi
  fi
  case $rest in
    *:*) rest=\${rest#*:} ;;
    *) break ;;
  esac
done
PATH=\${stripped:-$self_path}
export PATH`;

  return `#!/bin/sh
# Generated by Paseo. Routes ${realBinary} through CLIProxyAPI for terminal sessions.
# Bypass for a single run: ${CLIPROXYAPI_SHIM_DISABLE_ENV}=1 ${realBinary}
set -e

if [ "${bypassTest}" = "1" ] || ${passthroughTests}; then
${stripSelfFromPath}
  exec ${realBinary} "$@"
fi

${envExports}

${stripSelfFromPath}
exec ${realBinary} ${argv.map(shellQuote).join(" ")} "$@"
`;
}

function shimFileNameForPlatform(harness: ShimmedHarness): string {
  return process.platform === "win32" ? `${harness}.cmd` : harness;
}

/**
 * Write every shim into `paseoHome` and return the directory holding them.
 *
 * Writing is idempotent and atomic; a no-op gateway returns null so the caller
 * can skip PATH injection entirely. Called once per terminal create, so a
 * gateway edit reaches new terminals without a daemon restart.
 */
export function ensureHarnessShims(
  paseoHome: string,
  gateway: ResolvedGatewayConfig | null | undefined,
): string | null {
  if (!gateway) return null;
  const shimDirectory = resolveHarnessShimDirectory(paseoHome);
  for (const harness of SHIMMED_HARNESSES) {
    const filePath = join(shimDirectory, shimFileNameForPlatform(harness));
    const script =
      process.platform === "win32"
        ? buildCmdShimScript(harness, gateway)
        : buildShimScript(harness, gateway);
    writePrivateFileAtomicSync(filePath, script);
    if (process.platform !== "win32") {
      // writePrivateFileAtomicSync forces 0600; a shim must be executable.
      chmodSync(filePath, 0o700);
    }
  }
  return shimDirectory;
}

export function harnessShimExists(shimDirectory: string, harness: ShimmedHarness): boolean {
  return existsSync(join(shimDirectory, shimFileNameForPlatform(harness)));
}
