import { chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { writePrivateFileAtomicSync } from "../server/private-files.js";
import {
  buildHarnessShimEnv,
  CLIPROXYAPI_SHIM_DISABLE_ENV,
  SHIMMED_HARNESSES,
  type ShimmedHarness,
} from "./harness-shims.js";
import type { ResolvedGatewayConfig } from "../server/agent/gateway/config.js";

/**
 * Generates the terminal harness shims into a private per-daemon directory and
 * prepends that directory to terminal PATH.
 *
 * The generated script is a POSIX `sh` wrapper. It resolves the real binary
 * from PATH with its own directory removed, so a shim can never recurse into
 * itself, then execs it with the gateway env and argv applied.
 */

const SHIM_DIR_BASENAME = "harness-shims";

/** Directory name of the real binary each shim must exec, past itself. */
const REAL_BINARY: Record<ShimmedHarness, string> = {
  claude: "claude",
  codex: "codex",
  opencode: "opencode",
};

function shimDirNameForPlatform(): string {
  // Windows shims need a .cmd wrapper; POSIX needs a bare executable.
  return process.platform === "win32" ? "cmd-shims" : SHIM_DIR_BASENAME;
}

export function resolveHarnessShimDirectory(paseoHome: string): string {
  return join(paseoHome, shimDirNameForPlatform());
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Emit a cmd.exe shim.
 *
 * Windows resolves a bare `claude` to `claude.cmd` before `claude.exe`, so the
 * wrapper is on PATH ahead of the real binary. The PATH is rewritten in-process
 * to drop this shim's own directory before the real binary is launched, which is
 * what stops `claude` from re-entering this file.
 */
function buildCmdShimScript(harness: ShimmedHarness, gateway: ResolvedGatewayConfig): string {
  const { env, argv } = buildHarnessShimEnv(harness, gateway);
  const realBinary = `${REAL_BINARY[harness]}.exe`;

  // PATH is captured with delayed expansion deliberately: %PATH% alone expands
  // before the loop below rewrites it, so every iteration would re-add the
  // entries already removed.
  const envLines = Object.entries(env).map(
    ([key, value]) => `set "${key}=${value.replace(/(["\r\n])/g, "^$1")}"`,
  );

  const stripSelfFromPath = [
    `set "self_path=%PATH%"`,
    `set "self_dir=%~dp0"`,
    `set "rest=%PATH%"`,
    `set "stripped="`,
    `for /f "tokens=1* delims=:" %%A in ("%rest%") do (`,
    `  if /I not "%%A"=="" call :keepEntry "%%A"`,
    `  set "rest=%%B"`,
    `  if not defined rest goto pathDone`,
    `)`,
    `call :stripDone`,
    `:keepEntry`,
    `set "entry=%~1"`,
    // Defensive: the dir is quoted only when it needs quoting, so a plain
    // "%self_dir%\\" comparison never matches a bare path.
    `if /I "%entry:~-1%"=="\\" set "entry=%entry:~0,-1%"`,
    `if /I "%entry%"=="%self_dir%" exit /b 0`,
    `if not defined stripped (`,
    `  set "stripped=%entry%"`,
    `) else (`,
    `  set "stripped=%stripped%;%entry%"`,
    `)`,
    `exit /b 0`,
    `:stripDone`,
    `if defined stripped (`,
    `  set "PATH=%stripped%"`,
    `) else (`,
    `  set "PATH=%self_path%"`,
    `)`,
    `exit /b 0`,
    `:pathDone`,
  ].join("\r\n");

  return [
    "@echo off",
    `rem Generated by Paseo. Routes ${REAL_BINARY[harness]} through CLIProxyAPI for terminal sessions.`,
    `rem Bypass for a single run: set ${CLIPROXYAPI_SHIM_DISABLE_ENV}=1 && ${REAL_BINARY[harness]}`,
    `if "%${CLIPROXYAPI_SHIM_DISABLE_ENV}%"=="1" goto bypass`,
    ...envLines,
    stripSelfFromPath,
    `${realBinary} ${argv.map(quoteCmdArg).join(" ")} %*`,
    "exit /b %ERRORLEVEL%",
    ":bypass",
    stripSelfFromPath,
    `${realBinary} %*`,
    "exit /b %ERRORLEVEL%",
    "",
  ].join("\r\n");
}

function quoteCmdArg(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

/**
 * Emit a POSIX sh shim that execs the real binary with gateway env applied.
 *
 * `selfDir` is stripped from PATH so `command -v` skips this wrapper; without
 * that the shim resolves itself and recurses forever.
 */
function buildShimScript(harness: ShimmedHarness, gateway: ResolvedGatewayConfig): string {
  const { env, argv } = buildHarnessShimEnv(harness, gateway);
  const realBinary = REAL_BINARY[harness];

  const envExports = Object.entries(env)
    .map(([key, value]) => `export ${key}=${shellQuote(value)}`)
    .join("\n");

  const bypassTest = `\${${CLIPROXYAPI_SHIM_DISABLE_ENV}:-}`;

  // Drop this shim's own directory from PATH so `command -v` finds the real
  // binary instead of this wrapper. Without it the shim execs itself forever.
  //
  // Pure parameter expansion, deliberately: an earlier version piped PATH
  // through dirname/tr/grep/paste, but those run *after* PATH is rewritten and
  // vanished under a minimal PATH, breaking every invocation. The original
  // PATH is stashed in self_path and only the child inherits the stripped one.
  //
  // self_dir is derived from $0, which every common shell (sh, bash, dash, zsh)
  // fills with the PATH-resolved path even for a bare `claude`. Deriving it
  // from an env var instead would be a second source of truth for no gain.
  const stripSelfFromPath = `self_dir=\${0%/*}
self_path=$PATH
stripped=
rest=$PATH
while [ -n "$rest" ]; do
  entry=\${rest%%:*}
  if [ -n "$entry" ] && [ "$entry" != "$self_dir" ]; then
    if [ -n "$stripped" ]; then stripped=$stripped:$entry; else stripped=$entry; fi
  fi
  case $rest in
    *:*) rest=\${rest#*:} ;;
    *) break ;;
  esac
done
PATH=\${stripped:-$self_path}
export PATH`;

  return `#!/bin/sh
# Generated by Paseo. Routes ${realBinary} through CLIProxyAPI for terminal sessions.
# Bypass for a single run: ${CLIPROXYAPI_SHIM_DISABLE_ENV}=1 ${realBinary}
set -e

if [ "${bypassTest}" = "1" ]; then
${stripSelfFromPath}
  exec ${realBinary} "$@"
fi

${envExports}

${stripSelfFromPath}
exec ${realBinary} ${argv.map(shellQuote).join(" ")} "$@"
`;
}

function shimFileNameForPlatform(harness: ShimmedHarness): string {
  return process.platform === "win32" ? `${harness}.cmd` : harness;
}

/**
 * Write every shim into `paseoHome` and return the directory holding them.
 *
 * Writing is idempotent and atomic; a no-op gateway returns null so the caller
 * can skip PATH injection entirely. Called once per terminal create, so a
 * gateway edit reaches new terminals without a daemon restart.
 */
export function ensureHarnessShims(
  paseoHome: string,
  gateway: ResolvedGatewayConfig | null | undefined,
): string | null {
  if (!gateway) return null;
  const shimDirectory = resolveHarnessShimDirectory(paseoHome);
  for (const harness of SHIMMED_HARNESSES) {
    const filePath = join(shimDirectory, shimFileNameForPlatform(harness));
    const script =
      process.platform === "win32"
        ? buildCmdShimScript(harness, gateway)
        : buildShimScript(harness, gateway);
    writePrivateFileAtomicSync(filePath, script);
    if (process.platform !== "win32") {
      // writePrivateFileAtomicSync forces 0600; a shim must be executable.
      chmodSync(filePath, 0o700);
    }
  }
  return shimDirectory;
}

export function harnessShimExists(shimDirectory: string, harness: ShimmedHarness): boolean {
  return existsSync(join(shimDirectory, shimFileNameForPlatform(harness)));
}
